version: '3.1'
services:
    mongo:
        command: mongod --auth
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: test
        volumes:
            - mongodb:/var/lib/mongodb
    node:
        image: node:12.16.3-alpine3.11
        depends_on:
            - mongo
            - redis
        volumes:
            - ./:/srv
        working_dir: /srv
    redis:
        image: redis:4.0.10-alpine

volumes:
    mongodb:
