name: Test & Coverage Message Queue

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: npm ci

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: npm run docker run test:badges
      
      - uses: actions/checkout@master

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true