name: Test & Coverage Message Queue

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: npm ci

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: npm run docker run test:badges

      - name: Update README
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with: 
          file_pattern: '.badges/*'
          commit_message: 'Doc(readme): Update badges with last coverage'
          branch: ${{ github.head_ref }}